# Main file

# Run independent playbooks
- import_playbook: ./playbooks/prep_ansible_host.yml
- import_playbook: ./playbooks/apt.yml

- name: Run roles
  hosts: "ubuntu"
  become: true
  roles:
    - auto_update
    - base_packages
    - timezone
    # - silent_motd
    # - list_installed_packages
