---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Run unattended-upgrades for security patches only
  ansible.builtin.command:
    cmd: unattended-upgrade --verbose

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Configure fail2ban bantime and escalation
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/customisations.local
    content: |
      [DEFAULT]
      bantime = 1h
      bantime.increment = true
  notify: Restart fail2ban

- name: Enable and start fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
