---
- name: Install Sealed Secrets controller
  shell: >
    kubectl apply -f
    https://github.com/bitnami-labs/sealed-secrets/releases/download/v{{ sealed_secrets_version }}/controller.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Wait for Sealed Secrets controller to be ready
  shell: >
    kubectl rollout status deployment/sealed-secrets-controller
    -n kube-system --timeout=120s
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
