---
# tasks file for auto_update
- name: Install unattended-upgrades and update-notifier-common
  apt:
    name:
      - unattended-upgrades
      - update-notifier-common
    state: present
    update_cache: yes

- name: Enable unattended-upgrades
  command: dpkg-reconfigure -plow unattended-upgrades
  args:
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Configure unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
      };


# Update the apy-daily manually.
- name: Set update frequency
  template:
    src: "template/apt-daily.timer.j2"
    dest: /etc/systemd/system/apt-daily.timer

- name: Set upgrade frequency
  template:
    src: "template/apt-daily-upgrade.timer.j2"
    dest: /etc/systemd/system/apt-daily-upgrade.timer

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Restart apt-daily.timer
  command: systemctl restart apt-daily.timer

- name: Enable apt-daily.timer
  command: systemctl enable apt-daily-upgrade.timer

- name: Restart apt-daily-upgrade.timer
  command: systemctl restart apt-daily-upgrade.timer

- name: Enable apt-daily-upgrade.timer
  command: systemctl enable apt-daily-upgrade.timer


# Frequency Breakdown
# Daily: The value “1” indicates that the task will be performed every day.
# Weekly: If you set the value to “7”, the task would be performed once a week.
# Monthly: If you set the value to “30”, the task would be performed once a month

# - name: Set update frequency
#   copy:
#     dest: /etc/apt/apt.conf.d/20auto-upgrades
#     content: |
#       APT::Periodic::Update-Package-Lists "1";
#       APT::Periodic::Unattended-Upgrade "1";

# # Schedule Cron Job: Uses the cron module to schedule the unattended-upgrade command to run at 02:00 .
# - name: Schedule unattended-upgrade to run at 02:00 daily
#   cron:
#     name: "unattended-upgrade"
#     minute: "0"
#     hour: "2"
#     job: "/usr/bin/unattended-upgrade"
#     user: root

# Modified
# - name: Set update frequency
#   template:
#     src: "template/20auto-upgrades.j2"
#     dest: /etc/apt/apt.conf.d/20auto-upgrades
    
# Schedule Cron Job: Uses the cron module to schedule the unattended-upgrade command to run at.
# - name: Schedule unattended-upgrade to run at
#   cron:
#     name: "unattended-upgrade"
#     minute: "{{ time['minutes'] }}"
#     hour: "{{ time['hour'] }}"
#     job: "/usr/bin/unattended-upgrade"
#     user: root