---
- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: Enable unattended-upgrades
  command: dpkg-reconfigure -plow unattended-upgrades
  args:
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Configure unattended-upgrades (security only)
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}-security";
        "${distro_id}ESM:${distro_codename}-infra-security";
      };
      Unattended-Upgrade::Package-Blacklist {
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "false";

- name: Set update frequency
  template:
    src: "template/apt-daily.timer.j2"
    dest: /etc/systemd/system/apt-daily.timer

- name: Set upgrade frequency
  template:
    src: "template/apt-daily-upgrade.timer.j2"
    dest: /etc/systemd/system/apt-daily-upgrade.timer

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and restart apt-daily.timer
  systemd:
    name: apt-daily.timer
    state: restarted
    enabled: yes

- name: Enable and restart apt-daily-upgrade.timer
  systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    enabled: yes
