- name: Update and Upgrade APT Packages
  hosts: "ubuntu"
  become: true
  tasks:
    - name: Update the APT package index
      apt:
        update_cache: "yes"

    - name: Upgrade all APT packages
      apt:
        upgrade: "yes"
        autoclean: "yes"
        autoremove: "yes"
