- name: Install Ansible Host
  hosts: "ansible_host"
  become: true
  tasks:
    - name: Ensure python3 and python3-pip
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip

    - name: Upgrade pip
      ansible.builtin.command:
        cmd: python3 -m pip install --upgrade pip

    - name: Install Ansible
      ansible.builtin.pip:
        name: ansible
